web:
  build: .
  command: 'bash -c ''freechessclub'''
  working_dir: /app/user/src/github.com/freechessclub/freechessclub
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user/src/github.com/freechessclub/freechessclub
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user/src/github.com/freechessclub/freechessclub'
